### ISSUE TITLE
Stop Spin According to Value

### ISSUE THREAD

**Issue by dhairyacretive** [thanhniencung/LuckyWheel#2]
Hi, i Want to stop spinning using value instead of index position.

**Comment by thanhniencung** [comment]
you should write a function with parameter is index posistion and return value according with, like this : luckyWheelView.startLuckyWheelWithTargetIndex(getIndexByValue(value));

**Comment by dhairyacretive** [comment]
thnx :)

**Comment by tyogunawan23** [comment]
can we use this lib ? in my project ?
